
name: pytest

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest -v --browser ${{ matrix.browser }} --html=report.html --self-contained-html
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report-${{ matrix.browser }}
          path: report.html
